-- 1. PROFILES
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  role text check (role in ('user', 'organizer', 'super_admin')) default 'user',

  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check ((select auth.uid()) = id);
create policy "Users can update own profile." on profiles for update using ((select auth.uid()) = id);

create function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', COALESCE(new.raw_user_meta_data->>'role', 'user'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- 2. EVENTS (Updated)
-- 2. EVENTS (Updated)
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  location text,
  date timestamp with time zone,
  price numeric default 0,
  image_url text,
  category text, 
  is_active boolean default true, 
  organizer_id uuid references auth.users not null
);

alter table events enable row level security;

create policy "Events are viewable by everyone." on events for select using (true);
create policy "Authenticated users can create events." on events for insert with check (auth.role() = 'authenticated');
create policy "Organizers can update their own events." on events for update using (auth.uid() = organizer_id);
create policy "Organizers can delete their own events." on events for delete using (auth.uid() = organizer_id);

-- 3. TICKET TIERS
create table ticket_tiers (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade not null,
  name text not null,
  price numeric default 0,
  quota int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table ticket_tiers enable row level security;
create policy "Ticket tiers viewable by everyone" on ticket_tiers for select using (true);
create policy "Organizers can insert tiers" on ticket_tiers for insert with check (auth.role() = 'authenticated'); 
create policy "Organizers can update tiers" on ticket_tiers for update using (auth.role() = 'authenticated');

-- 4. TICKETS (Transactions)
create table tickets (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) not null,
  user_id uuid references auth.users not null,
  tier_id bigint references ticket_tiers(id) not null,
  quantity int default 1,
  total_price numeric not null,
  status text default 'valid',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table tickets enable row level security;
create policy "Users can view their own tickets" on tickets for select using (auth.uid() = user_id);
create policy "Users can buy tickets" on tickets for insert with check (auth.uid() = user_id);
create policy "Organizers can view tickets for their events" on tickets for select using (
  exists (select 1 from events where events.id = tickets.event_id and events.organizer_id = auth.uid())
);

-- 5. STORAGE POLICIES (Run this if you created 'event-images' bucket)
-- insert into storage.buckets (id, name, public) values ('event-images', 'event-images', true);
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'event-images' );
-- create policy "Authenticated Upload" on storage.objects for insert with check ( bucket_id = 'event-images' and auth.role() = 'authenticated' );

-- 6. TRANSACTIONS (New)
create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_id bigint references events(id),
  tier_name text,
  quantity int default 1,
  total_price numeric,
  status text,
  midtrans_id text,
  user_id uuid references auth.users
);

alter table transactions enable row level security;

create policy "Enable insert for everyone" on transactions for insert with check (true);

create policy "Organizers can view transactions" on transactions for select using (
  exists (
    select 1 from events 
    where events.id = transactions.event_id 
    and events.organizer_id = auth.uid()
  )
);

create policy "Users can view own transactions" on transactions for select using (
  auth.uid() = user_id
);
