-- Create transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_id bigint references events(id),
  tier_name text,
  quantity int default 1,
  total_price numeric,
  status text,
  midtrans_id text,
  user_id uuid references auth.users -- Optional if we allow guest checkout
);

-- Enable Row Level Security
alter table transactions enable row level security;

-- Policies
-- 1. Everyone can insert (for public checkout) - might want to restrict if auth only
create policy "Enable insert for everyone" on transactions for insert with check (true);

-- 2. Organizer can view transactions for their events
create policy "Organizers can view transactions" on transactions for select using (
  exists (
    select 1 from events 
    where events.id = transactions.event_id 
    and events.organizer_id = auth.uid()
  )
);

-- 3. Users can view their own transactions
create policy "Users can view own transactions" on transactions for select using (
  auth.uid() = user_id
);
